# Generated by Django 2.1.2 on 2018-11-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='perrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Media')),
                ('Nombre', models.CharField(max_length=100)),
                ('Raza', models.CharField(max_length=50)),
                ('Descripcion', models.TextField(max_length=1000)),
            ],
        ),
    ]
