# Generated by Django 2.1.2 on 2018-11-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_perrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='perrito',
        ),
    ]
