# Generated by Django 2.1.2 on 2018-11-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20181118_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='Clave',
            field=models.CharField(max_length=16),
        ),
    ]
