# Generated by Django 2.1.2 on 2018-12-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20181210_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='TecnicoAsignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tecnico'),
        ),
    ]
