# Generated by Django 2.1.2 on 2018-12-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20181211_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='NombreCliente',
            field=models.CharField(max_length=100),
        ),
    ]
